server:
  command: "php public/index.php"
  env:
    - DB: mysql
http:
  address: "0.0.0.0:8080"
  access_logs: true
  pool:
    num_workers: 4
    debug: true
logs:
  mode: development
  level: debug
  output: stderr