language: php
php:
  - 7.2
  - 7.3
  - 7.4
sudo: false
services:
  - mysql
install:
  - composer install
  - ./vendor/bin/rr get-binary
before_script:
  - mysql -e 'create database psx;'
  - ./rr serve -v -d &
  - sleep 6
script:
  - SEND=external vendor/bin/phpunit
env:
  - DB=mysql
