name: CI
on:
  - pull_request
  - push
jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none
      - name: Composer install
        run: composer install --no-interaction --no-ansi --no-progress
      - name: Run Psalm
        run: vendor/bin/psalm --no-progress --shepherd --show-info=false --stats
  phpunit:
    name: "PHPUnit (PHP: ${{ matrix.php-versions }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions:
         - 8.0
         - 8.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
      - name: Setup MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e "CREATE DATABASE fusio;" -uroot -proot
          mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'test1234';" -uroot -proot
      - name: Composer install
        run: composer install --no-interaction --no-ansi --no-progress
      - name: Roadrunner install
        run: ./vendor/bin/rr get-binary
      - name: Run Roadrunner
        run: ./rr serve -v -d &
      - name: Wait
        run: sleep 6
      - name: Run PHPUnit
        run: vendor/bin/phpunit
